export const ST = {
  app: { minHeight: "100vh", background: "#F7F7F5", color: "#17181C", fontFamily: "'Public Sans', sans-serif", overflowX: "hidden" },
  header: { background: "#FFFFFF", borderBottom: "1px solid #E4E4E0", position: "sticky", top: 0, zIndex: 50 },
  headerInner: { maxWidth: 1100, margin: "0 auto", padding: "0 20px" },
  headerRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 0 10px" },
  brand: { fontFamily: "'Fraunces', serif", fontWeight: 700, fontSize: 21, letterSpacing: "-0.01em" },
  brandSub: { fontSize: 12, color: "#6E7079", marginTop: 1 },
  newDayBtn: { background: "#0B6E4F", color: "#fff", border: "none", borderRadius: 8, padding: "8px 16px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  dayNav: { display: "flex", alignItems: "center", gap: 10, padding: "0 0 10px" },
  monthSelect: { flexShrink: 0, border: "1px solid #E4E4E0", borderRadius: 8, padding: "6px 10px", fontSize: 13, fontWeight: 600, fontFamily: "'Public Sans', sans-serif", background: "#fff", color: "#17181C", cursor: "pointer" },
  dayScroll: { display: "flex", gap: 6, overflowX: "auto", flex: 1 },
  dayChip: { flexShrink: 0, padding: "6px 12px", borderRadius: 20, border: "1px solid #E4E4E0", background: "#fff", color: "#6E7079", fontSize: 12.5, fontFamily: "'IBM Plex Mono', monospace", cursor: "pointer" },
  dayChipActive: { background: "#0B6E4F", borderColor: "#0B6E4F", color: "#fff" },
  tabBar: { display: "flex", borderTop: "1px solid #E4E4E0", gap: 6, padding: "12px 0", overflowX: "auto" },
  tabBtn: { padding: "8px 16px", background: "none", border: "none", color: "#6E7079", fontWeight: 600, fontSize: 13, cursor: "pointer", whiteSpace: "nowrap", outline: "none", WebkitTapHighlightColor: "transparent", borderRadius: 20 },
  tabBtnActive: { color: "#0B6E4F", background: "#E7F3EF" },
  main: { padding: "16px 20px 60px", maxWidth: 1100, margin: "0 auto" },

  pastNotice: { background: "#FBF3D9", border: "1px solid #E9D896", color: "#7A5C00", fontSize: 13, padding: "8px 14px", borderRadius: 8, marginBottom: 14 },

  segControl: { display: "inline-flex", background: "#EDECE7", borderRadius: 10, padding: 3, marginBottom: 16 },
  segBtn: { padding: "7px 16px", border: "none", background: "none", borderRadius: 8, fontSize: 13, fontWeight: 600, color: "#6E7079", cursor: "pointer" },
  segBtnActive: { background: "#fff", color: "#17181C", boxShadow: "0 1px 2px rgba(0,0,0,0.08)" },

  statsRow: { display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap" },
  statBox: { flex: "1 1 150px", background: "#fff", border: "1px solid #E4E4E0", borderRadius: 10, padding: "12px 16px" },
  statValue: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 20, fontWeight: 600 },
  statLabel: { fontSize: 11.5, color: "#6E7079", marginTop: 2, textTransform: "uppercase", letterSpacing: "0.06em" },

  note: { fontSize: 12.5, color: "#6E7079", marginBottom: 12, fontStyle: "italic" },

  tableWrap: { background: "#fff", border: "1px solid #E4E4E0", borderRadius: 10, overflowX: "auto" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: { padding: "10px 8px", textAlign: "right", color: "#6E7079", fontWeight: 600, fontSize: 11, textTransform: "uppercase", letterSpacing: "0.04em", borderBottom: "1px solid #E4E4E0", whiteSpace: "nowrap" },
  td: { padding: "8px", textAlign: "right", borderBottom: "1px solid #F0F0EC", fontFamily: "'IBM Plex Mono', monospace" },
  tdCalc: { color: "#6E7079" },
  rowEven: { background: "#fff" },
  rowOdd: { background: "#FBFBFA" },
  gradeTag: { fontSize: 10, color: "#9A9A93", marginLeft: 6, fontFamily: "'IBM Plex Mono', monospace" },

  input: { border: "1px solid #E4E4E0", borderRadius: 6, padding: "5px 7px", textAlign: "right", fontSize: 13, fontFamily: "'IBM Plex Mono', monospace", background: "#FCFCFB" },

  cardList: { display: "flex", flexDirection: "column", gap: 8 },
  card: { display: "flex", justifyContent: "space-between", alignItems: "center", background: "#fff", border: "1px solid #E4E4E0", borderRadius: 10, padding: "12px 14px", textAlign: "left", cursor: "pointer", width: "100%" },
  cardLeft: {},
  cardName: { fontWeight: 600, fontSize: 14.5 },
  cardSub: { fontSize: 12, color: "#6E7079", marginTop: 2 },
  cardBal: { fontFamily: "'IBM Plex Mono', monospace", fontWeight: 700, fontSize: 14 },

  overlay: { position: "fixed", inset: 0, background: "rgba(23,24,28,0.4)", display: "flex", alignItems: "flex-end", justifyContent: "center", zIndex: 200 },
  confirmModal: { background: "#fff", borderRadius: "16px 16px 0 0", padding: 22, width: "100%", maxWidth: 420, margin: "auto" },
  confirmTitle: { fontFamily: "'Fraunces', serif", fontWeight: 700, fontSize: 18, marginBottom: 8 },
  confirmBody: { fontSize: 13.5, color: "#4B4C52", lineHeight: 1.5, marginBottom: 18 },
  confirmActions: { display: "flex", gap: 10, justifyContent: "flex-end" },
  btnGhost: { background: "none", border: "1px solid #E4E4E0", borderRadius: 8, padding: "9px 16px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  btnPrimary: { background: "#0B6E4F", color: "#fff", border: "none", borderRadius: 8, padding: "9px 16px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  addLinkBtn: { background: "none", border: "none", color: "#0B6E4F", fontWeight: 600, cursor: "pointer", fontSize: 13, padding: "5px 0" },

  mobileModal: { background: "#fff", borderRadius: "16px 16px 0 0", padding: "18px 20px 28px", width: "100%", maxWidth: 480, margin: "auto", maxHeight: "85vh", overflowY: "auto" },
  mobileModalHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16, borderBottom: "1px solid #E4E4E0", paddingBottom: 14 },
  mobileModalName: { fontFamily: "'Fraunces', serif", fontWeight: 700, fontSize: 18 },
  mobileModalMeta: { fontSize: 12, color: "#6E7079", marginTop: 3, fontFamily: "'IBM Plex Mono', monospace" },
  closeBtn: { background: "#0B6E4F", color: "#fff", border: "none", borderRadius: 8, padding: "7px 14px", fontSize: 13, fontWeight: 600, cursor: "pointer" },
  checkboxRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 14, fontWeight: 600, marginBottom: 14 },
  mobileField: { marginBottom: 12 },
  mobileLabel: { display: "block", fontSize: 12, color: "#6E7079", marginBottom: 4, fontWeight: 600 },
  mobileResult: { marginTop: 14, paddingTop: 14, borderTop: "1px solid #E4E4E0", display: "flex", flexDirection: "column", gap: 6, fontSize: 13.5 },

  summaryGrid: { display: "flex", flexDirection: "column", gap: 14 },
  card2: { background: "#fff", border: "1px solid #E4E4E0", borderRadius: 10, padding: 18 },
  cardTitle: { fontFamily: "'Fraunces', serif", fontWeight: 700, fontSize: 15, marginBottom: 12, paddingBottom: 10, borderBottom: "1px solid #E4E4E0" },
  summaryList: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 12 },
  summaryRow: { display: "flex", justifyContent: "space-between", fontSize: 13, padding: "5px 0", borderBottom: "1px solid #F5F5F2" },
  summaryFooterRow: { display: "flex", justifyContent: "space-between", fontSize: 14, padding: "6px 0" },
  weekLabel: { fontSize: 12, fontWeight: 700, color: "#0B6E4F", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.04em" },
  monthRow: { display: "flex", justifyContent: "space-between", fontSize: 12.5, padding: "6px 0", borderBottom: "1px solid #F5F5F2", fontFamily: "'IBM Plex Mono', monospace" },

  workerGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(190px,1fr))", gap: 10 },
  workerCard: { background: "#fff", border: "1px solid #E4E4E0", borderRadius: 10, padding: 14 },
  wcName: { fontWeight: 700, marginBottom: 8 },
  wcRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8, fontSize: 12.5 },
  wcLabel: { color: "#6E7079" },
  wcInput: { width: 64, border: "1px solid #E4E4E0", borderRadius: 6, padding: "3px 6px", textAlign: "right", fontFamily: "'IBM Plex Mono', monospace" },
  wcToggle: { width: "100%", background: "none", border: "1px solid #E4E4E0", borderRadius: 6, padding: "5px", fontSize: 12, cursor: "pointer", color: "#6E7079" },

  addRow: { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" },
  addInput: { flex: "1 1 160px", border: "1px solid #E4E4E0", borderRadius: 8, padding: "9px 12px", fontSize: 13 },
  addSelect: { border: "1px solid #E4E4E0", borderRadius: 8, padding: "9px 12px", fontSize: 13, background: "#fff" },

  auditList: { display: "flex", flexDirection: "column", gap: 8 },
  auditRow: { background: "#fff", border: "1px solid #E4E4E0", borderRadius: 8, padding: "10px 14px", fontSize: 13 },
  auditMeta: { display: "flex", justifyContent: "space-between", fontSize: 11, color: "#9A9A93", marginBottom: 4 },
  auditDate: { fontFamily: "'IBM Plex Mono', monospace" },
  auditDiff: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12.5, marginTop: 3 },
  auditOld: { color: "#C0392B" },
  auditNew: { color: "#1B8A5A" },
};
